version: '3'
services:
  db:
    image: mysql
    container_name: mysqldb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  web-service:
    build: .
    container_name: items-demo
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/test'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 15s
      timeout: 5s
      retries: 3
volumes:
  db_data: